"""Prove the package refuses to import an engine whose bytes are not published.

The self-check in `__init__.py` is only worth having if it actually fires, so
every case here builds a minimal tree, mutates exactly one thing, and imports in
a subprocess -- the parent process has already imported the real package, and an
in-process test would prove nothing about a fresh interpreter.

    python -B receiver_reliance/test_engine_manifest.py
"""
from __future__ import annotations

import json
import pathlib
import hashlib
import shutil
import subprocess
import sys
import tempfile
import unittest

HERE = pathlib.Path(__file__).resolve().parent
REPO = HERE.parent
PACKAGE_FILES = ("__init__.py", "engine_manifest.json", "generate_engine_manifest.py", "conformance.py")


def stage(destination: pathlib.Path, *, engine_subdir: bool = False) -> pathlib.Path:
    """Build the smallest tree that can import the package.

    With engine_subdir the engine lands under receiver_reliance/_engine/, which is
    the self-contained-distribution layout; otherwise it lands beside the package,
    which is the repo-checkout layout.
    """
    manifest = json.loads((HERE / "engine_manifest.json").read_text(encoding="utf-8"))
    package = destination / "receiver_reliance"
    package.mkdir(parents=True)
    for name in PACKAGE_FILES:
        source = HERE / name
        if source.is_file():
            shutil.copy2(source, package / name)
    engine_root = (package / "_engine") if engine_subdir else destination
    for record in manifest["files"]:
        target = engine_root.joinpath(*record["path"].split("/"))
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(REPO.joinpath(*record["path"].split("/")), target)
    return engine_root


def import_in_subprocess(root: pathlib.Path) -> subprocess.CompletedProcess[str]:
    """Import the staged package in a fresh isolated interpreter.

    -I ignores PYTHONPATH by design, so the staged root is injected into sys.path
    in-process rather than through the environment.
    """
    program = (
        "import sys; sys.path.insert(0, %r); "
        "import receiver_reliance as rr; print(rr.ENGINE_MANIFEST_SHA256)" % str(root)
    )
    return subprocess.run(
        [sys.executable, "-I", "-B", "-c", program],
        cwd=root,
        capture_output=True,
        text=True,
        check=False,
    )


class EngineManifestTests(unittest.TestCase):
    def test_committed_manifest_matches_the_engine_bytes(self) -> None:
        result = subprocess.run(
            [sys.executable, "-I", "-B", str(HERE / "generate_engine_manifest.py"), "--check"],
            capture_output=True, text=True, check=False,
        )
        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
        self.assertIn("exact generated bytes", result.stdout)

    def test_checkout_layout_imports_and_reports_the_manifest_digest(self) -> None:
        manifest = json.loads((HERE / "engine_manifest.json").read_text(encoding="utf-8"))
        with tempfile.TemporaryDirectory() as raw:
            root = pathlib.Path(raw)
            stage(root)
            result = import_in_subprocess(root)
            self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
            self.assertEqual(result.stdout.strip(), manifest["manifest_sha256"])

    def test_bundled_engine_layout_imports(self) -> None:
        """The self-contained layout must work without a repo checkout beside it."""
        manifest = json.loads((HERE / "engine_manifest.json").read_text(encoding="utf-8"))
        with tempfile.TemporaryDirectory() as raw:
            root = pathlib.Path(raw)
            stage(root, engine_subdir=True)
            self.assertFalse((root / "grounded-0_4").exists())
            result = import_in_subprocess(root)
            self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
            self.assertEqual(result.stdout.strip(), manifest["manifest_sha256"])

    def test_one_appended_byte_in_any_engine_file_refuses_import(self) -> None:
        manifest = json.loads((HERE / "engine_manifest.json").read_text(encoding="utf-8"))
        for record in manifest["files"]:
            with self.subTest(engine_file=record["path"]):
                with tempfile.TemporaryDirectory() as raw:
                    root = pathlib.Path(raw)
                    stage(root)
                    target = root.joinpath(*record["path"].split("/"))
                    target.write_bytes(target.read_bytes() + b"\n")
                    result = import_in_subprocess(root)
                    self.assertNotEqual(result.returncode, 0)
                    self.assertIn("engine drift", result.stderr)
                    self.assertIn(record["path"], result.stderr)

    def test_absent_entry_point_reports_it_cannot_locate_the_engine(self) -> None:
        """Losing rr_api.py means no layout resolves; that is a distinct message."""
        with tempfile.TemporaryDirectory() as raw:
            root = pathlib.Path(raw)
            stage(root)
            root.joinpath(*"grounded-0_4/rr_api.py".split("/")).unlink()
            result = import_in_subprocess(root)
            self.assertNotEqual(result.returncode, 0)
            self.assertIn("cannot locate its engine", result.stderr)

    def test_absent_non_entry_engine_file_names_the_missing_file(self) -> None:
        """Every other manifested file must be reported by name when absent."""
        manifest = json.loads((HERE / "engine_manifest.json").read_text(encoding="utf-8"))
        for record in manifest["files"]:
            if record["path"] == "grounded-0_4/rr_api.py":
                continue
            with self.subTest(engine_file=record["path"]):
                with tempfile.TemporaryDirectory() as raw:
                    root = pathlib.Path(raw)
                    stage(root)
                    root.joinpath(*record["path"].split("/")).unlink()
                    result = import_in_subprocess(root)
                    self.assertNotEqual(result.returncode, 0)
                    self.assertIn("engine file absent", result.stderr)
                    self.assertIn(record["path"], result.stderr)

    def test_absent_manifest_refuses_import(self) -> None:
        with tempfile.TemporaryDirectory() as raw:
            root = pathlib.Path(raw)
            stage(root)
            (root / "receiver_reliance" / "engine_manifest.json").unlink()
            result = import_in_subprocess(root)
            self.assertNotEqual(result.returncode, 0)
            self.assertIn("engine manifest absent", result.stderr)

    def test_manifest_covers_every_file_the_engine_actually_opens(self) -> None:
        """Re-derive the closure by tracing; a read the manifest omits is unverified.

        An earlier version of this test matched filenames inside rr_api.py and
        passed while the manifest was missing four files, because two of them are
        opened by b1_capabilities.authority_documents() and never named in
        rr_api.py at all. Reading the source is not a substitute for watching
        what the process opens.
        """
        program = (
            "import pathlib, sys, json\n"
            "REPO = pathlib.Path(%r).resolve()\n"
            "seen = set()\n"
            "def hook(event, args):\n"
            "    if event != 'open':\n"
            "        return\n"
            "    try:\n"
            "        resolved = pathlib.Path(args[0]).resolve()\n"
            "    except (TypeError, OSError):\n"
            "        return\n"
            "    try:\n"
            "        relative = resolved.relative_to(REPO)\n"
            "    except ValueError:\n"
            "        return\n"
            "    if resolved.is_file():\n"
            "        seen.add(relative.as_posix())\n"
            "sys.addaudithook(hook)\n"
            "import receiver_reliance as rr\n"
            "rr.decide_audited({'operation': 'OBL-01'})\n"
            "print(json.dumps(sorted(seen)))\n" % str(REPO)
        )
        result = subprocess.run(
            [sys.executable, "-B", "-c", program], cwd=REPO, capture_output=True, text=True, check=False
        )
        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
        opened = json.loads(result.stdout.strip().splitlines()[-1])
        engine_reads = {
            path
            for path in opened
            if not path.startswith("receiver_reliance/") and "__pycache__" not in path
        }
        manifest = json.loads((HERE / "engine_manifest.json").read_text(encoding="utf-8"))
        covered = {record["path"] for record in manifest["files"]}
        self.assertEqual(
            engine_reads - covered,
            set(),
            "the engine opens files the manifest does not verify",
        )
        self.assertEqual(
            covered - engine_reads,
            set(),
            "the manifest verifies files the engine never opens",
        )


class ManifestIsAmbiguityProof(unittest.TestCase):
    """The manifest is the gate's own input; a drifted manifest must not pass.

    Until v1.2.2 this gate parsed the manifest with a bare `json.loads` and never
    recomputed its self-seal. `json.loads` keeps the LAST value for a repeated
    key, so a manifest carrying the real eleven rows followed by eleven forged
    ones satisfied `len(records) == file_count` and the loader then verified
    engine bytes against the forged digests -- while a human reading the file saw
    the real ones. Each arm below fails without its corresponding repair.
    """

    def _staged(self, root: pathlib.Path) -> pathlib.Path:
        stage(root)
        return root / "receiver_reliance" / "engine_manifest.json"

    def test_a_duplicate_member_is_refused(self) -> None:
        real = json.loads((HERE / "engine_manifest.json").read_text(encoding="utf-8"))
        forged = [
            {"path": f["path"], "byte_length": 1, "sha256": "0" * 64}
            for f in real["files"]
        ]
        blob = (
            '{"file_count": %d, "files": %s, "files": %s, "format_version": %s, '
            '"manifest_sha256": %s, "total_byte_length": %d}'
            % (
                real["file_count"],
                json.dumps(real["files"]),
                json.dumps(forged),
                json.dumps(real["format_version"]),
                json.dumps(real["manifest_sha256"]),
                real["total_byte_length"],
            )
        )
        with tempfile.TemporaryDirectory() as raw:
            root = pathlib.Path(raw)
            self._staged(root).write_text(blob, encoding="utf-8")
            result = import_in_subprocess(root)
            self.assertNotEqual(result.returncode, 0)
            self.assertIn("duplicate object key", result.stdout + result.stderr)

    def test_an_edited_manifest_fails_its_own_self_seal(self) -> None:
        real = json.loads((HERE / "engine_manifest.json").read_text(encoding="utf-8"))
        edited = dict(real)
        edited["files"] = [
            {"path": f["path"], "byte_length": 1, "sha256": "0" * 64}
            for f in real["files"]
        ]
        with tempfile.TemporaryDirectory() as raw:
            root = pathlib.Path(raw)
            self._staged(root).write_text(json.dumps(edited), encoding="utf-8")
            result = import_in_subprocess(root)
            self.assertNotEqual(result.returncode, 0)
            self.assertIn("self-seal does not match", result.stdout + result.stderr)

    def test_a_resealed_forgery_still_fails_on_the_engine_bytes(self) -> None:
        """Defence in depth: a forger who reseals correctly still loses on bytes."""
        real = json.loads((HERE / "engine_manifest.json").read_text(encoding="utf-8"))
        forged = dict(real)
        forged["files"] = [
            {"path": f["path"], "byte_length": 1, "sha256": "0" * 64}
            for f in real["files"]
        ]
        probe = dict(forged)
        probe["manifest_sha256"] = "0" * 64
        forged["manifest_sha256"] = hashlib.sha256(
            json.dumps(
                probe,
                ensure_ascii=False,
                allow_nan=False,
                separators=(",", ":"),
                sort_keys=True,
            ).encode("utf-8")
        ).hexdigest().upper()
        with tempfile.TemporaryDirectory() as raw:
            root = pathlib.Path(raw)
            self._staged(root).write_text(json.dumps(forged), encoding="utf-8")
            result = import_in_subprocess(root)
            self.assertNotEqual(result.returncode, 0)
            self.assertIn("engine drift", result.stdout + result.stderr)

    def test_an_absent_self_seal_is_refused(self) -> None:
        real = json.loads((HERE / "engine_manifest.json").read_text(encoding="utf-8"))
        stripped = {k: v for k, v in real.items() if k != "manifest_sha256"}
        with tempfile.TemporaryDirectory() as raw:
            root = pathlib.Path(raw)
            self._staged(root).write_text(json.dumps(stripped), encoding="utf-8")
            result = import_in_subprocess(root)
            self.assertNotEqual(result.returncode, 0)
            self.assertIn("no self-seal", result.stdout + result.stderr)


if __name__ == "__main__":
    unittest.main(verbosity=2)
