"""Field contract rows transcribed verbatim from the frozen treatment-v6 semantic authority
(140172 B / SHA-256 E233C6373B34F11C5D12B51EAEE501F1042F46D87E2AE6853812790004F55AC8), document_schemas.COMMON.field_schema_rows
and document_schemas.STATE_{R,S,U}.field_schema_rows. Data only; the walker in admission.py applies
diagnostic_authority.atomic_target_projection over these rows. Generated by the custodian; do not edit by hand."""

from __future__ import annotations

COMMON_ROWS = [
 {
  "fields_exact": [
   "a2_raw_shared_bundle",
   "comparison_facts",
   "delivered_artifact_envelope",
   "format",
   "guard_observation_facts",
   "remediation",
   "requested_delivered_transfer",
   "source_lineage_observation",
   "task_id",
   "task_instruction_constraints"
  ],
  "pointer": "",
  "value_kind": "OBJECT"
 },
 {
  "accepted_schema_path": "access/A2_SHARED_DOMAIN_VOCABULARY_BASELINE_PROJECTION_0_1.schema.json",
  "accepted_schema_sha256": "1449369AE3CC4458F3F904ADCF0F24B0685E86C65EAC2AE656F7A3E4AD946460",
  "additional_properties": False,
  "pointer": "/a2_raw_shared_bundle",
  "value_kind": "OBJECT"
 },
 {
  "const": "RR-STUDY-TREATMENT-COMMON-5",
  "pointer": "/format",
  "value_kind": "STRING"
 },
 {
  "class_id": "IDENTIFIER",
  "pointer": "/task_id",
  "value_kind": "STRING"
 },
 {
  "fields_exact": [
   "carrier_fence",
   "consumed_representation_sha256",
   "current_fence",
   "expected_action_class",
   "expected_authority",
   "expected_carrier",
   "expected_direct_parents",
   "expected_generation",
   "expected_owner",
   "expected_principal",
   "expected_purpose",
   "expected_receiver_capability",
   "expected_representation_sha256",
   "expected_route",
   "expected_scope",
   "expected_slot",
   "observed_action_class",
   "observed_authority",
   "observed_carrier",
   "observed_direct_parents",
   "observed_generation",
   "observed_owner",
   "observed_principal",
   "observed_purpose",
   "observed_receiver_capability",
   "observed_route",
   "observed_scope",
   "observed_slot",
   "origin_finalized",
   "revocation_active",
   "use_time_ns",
   "valid_from_ns",
   "valid_until_ns"
  ],
  "pointer": "/comparison_facts",
  "value_kind": "OBJECT"
 },
 {
  "class_id": "SIGNED_NONNEGATIVE_INT64",
  "maximum": 9223372036854775807,
  "minimum": 0,
  "pointer": "/comparison_facts/carrier_fence",
  "value_kind": "INTEGER"
 },
 {
  "class_id": "SIGNED_NONNEGATIVE_INT64",
  "maximum": 9223372036854775807,
  "minimum": 0,
  "pointer": "/comparison_facts/current_fence",
  "value_kind": "INTEGER"
 },
 {
  "class_id": "SIGNED_NONNEGATIVE_INT64",
  "maximum": 9223372036854775807,
  "minimum": 0,
  "pointer": "/comparison_facts/expected_generation",
  "value_kind": "INTEGER"
 },
 {
  "class_id": "SIGNED_NONNEGATIVE_INT64",
  "maximum": 9223372036854775807,
  "minimum": 0,
  "pointer": "/comparison_facts/observed_generation",
  "value_kind": "INTEGER"
 },
 {
  "class_id": "SIGNED_NONNEGATIVE_INT64",
  "maximum": 9223372036854775807,
  "minimum": 0,
  "pointer": "/comparison_facts/use_time_ns",
  "value_kind": "INTEGER"
 },
 {
  "class_id": "SIGNED_NONNEGATIVE_INT64",
  "maximum": 9223372036854775807,
  "minimum": 0,
  "pointer": "/comparison_facts/valid_from_ns",
  "value_kind": "INTEGER"
 },
 {
  "class_id": "SIGNED_NONNEGATIVE_INT64",
  "maximum": 9223372036854775807,
  "minimum": 0,
  "pointer": "/comparison_facts/valid_until_ns",
  "value_kind": "INTEGER"
 },
 {
  "pointer": "/comparison_facts/origin_finalized",
  "value_kind": "BOOLEAN"
 },
 {
  "pointer": "/comparison_facts/revocation_active",
  "value_kind": "BOOLEAN"
 },
 {
  "class_id": "SHA256_UPPER",
  "pointer": "/comparison_facts/consumed_representation_sha256",
  "value_kind": "STRING"
 },
 {
  "class_id": "SHA256_UPPER",
  "pointer": "/comparison_facts/expected_representation_sha256",
  "value_kind": "STRING"
 },
 {
  "class_id": "ORDERED_IDENTIFIER_ARRAY",
  "maximum": 256,
  "minimum": 0,
  "pointer": "/comparison_facts/expected_direct_parents",
  "value_kind": "ARRAY"
 },
 {
  "class_id": "ORDERED_IDENTIFIER_ARRAY",
  "maximum": 256,
  "minimum": 0,
  "pointer": "/comparison_facts/observed_direct_parents",
  "value_kind": "ARRAY"
 },
 {
  "class_id": "SET_IDENTIFIER_ARRAY",
  "maximum": 256,
  "minimum": 1,
  "pointer": "/comparison_facts/expected_scope",
  "unique": True,
  "utf8_sorted": True,
  "value_kind": "ARRAY"
 },
 {
  "class_id": "SET_IDENTIFIER_ARRAY",
  "maximum": 256,
  "minimum": 1,
  "pointer": "/comparison_facts/observed_scope",
  "unique": True,
  "utf8_sorted": True,
  "value_kind": "ARRAY"
 },
 {
  "class_id": "IDENTIFIER",
  "pointer": "/comparison_facts/expected_action_class",
  "value_kind": "STRING"
 },
 {
  "class_id": "IDENTIFIER",
  "pointer": "/comparison_facts/expected_authority",
  "value_kind": "STRING"
 },
 {
  "class_id": "IDENTIFIER",
  "pointer": "/comparison_facts/expected_carrier",
  "value_kind": "STRING"
 },
 {
  "class_id": "IDENTIFIER",
  "pointer": "/comparison_facts/expected_owner",
  "value_kind": "STRING"
 },
 {
  "class_id": "IDENTIFIER",
  "pointer": "/comparison_facts/expected_principal",
  "value_kind": "STRING"
 },
 {
  "class_id": "IDENTIFIER",
  "pointer": "/comparison_facts/expected_purpose",
  "value_kind": "STRING"
 },
 {
  "class_id": "IDENTIFIER",
  "pointer": "/comparison_facts/expected_receiver_capability",
  "value_kind": "STRING"
 },
 {
  "class_id": "IDENTIFIER",
  "pointer": "/comparison_facts/expected_route",
  "value_kind": "STRING"
 },
 {
  "class_id": "IDENTIFIER",
  "pointer": "/comparison_facts/expected_slot",
  "value_kind": "STRING"
 },
 {
  "class_id": "IDENTIFIER",
  "pointer": "/comparison_facts/observed_action_class",
  "value_kind": "STRING"
 },
 {
  "class_id": "IDENTIFIER",
  "pointer": "/comparison_facts/observed_authority",
  "value_kind": "STRING"
 },
 {
  "class_id": "IDENTIFIER",
  "pointer": "/comparison_facts/observed_carrier",
  "value_kind": "STRING"
 },
 {
  "class_id": "IDENTIFIER",
  "pointer": "/comparison_facts/observed_owner",
  "value_kind": "STRING"
 },
 {
  "class_id": "IDENTIFIER",
  "pointer": "/comparison_facts/observed_principal",
  "value_kind": "STRING"
 },
 {
  "class_id": "IDENTIFIER",
  "pointer": "/comparison_facts/observed_purpose",
  "value_kind": "STRING"
 },
 {
  "class_id": "IDENTIFIER",
  "pointer": "/comparison_facts/observed_receiver_capability",
  "value_kind": "STRING"
 },
 {
  "class_id": "IDENTIFIER",
  "pointer": "/comparison_facts/observed_route",
  "value_kind": "STRING"
 },
 {
  "class_id": "IDENTIFIER",
  "pointer": "/comparison_facts/observed_slot",
  "value_kind": "STRING"
 },
 {
  "fields_exact": [
   "artifact_id",
   "content_b64",
   "format",
   "media_type",
   "revision"
  ],
  "pointer": "/delivered_artifact_envelope",
  "value_kind": "OBJECT"
 },
 {
  "class_id": "IDENTIFIER",
  "pointer": "/delivered_artifact_envelope/artifact_id",
  "value_kind": "STRING"
 },
 {
  "class_id": "CANONICAL_BASE64",
  "decoded_maximum": 32768,
  "decoded_minimum": 1,
  "pointer": "/delivered_artifact_envelope/content_b64",
  "value_kind": "STRING"
 },
 {
  "const": "RR-SCIENTIFIC-CLOSED-ARTIFACT-1",
  "pointer": "/delivered_artifact_envelope/format",
  "value_kind": "STRING"
 },
 {
  "enum": [
   "application/json",
   "text/plain"
  ],
  "pointer": "/delivered_artifact_envelope/media_type",
  "value_kind": "STRING"
 },
 {
  "class_id": "REVISION",
  "maximum": 2147483647,
  "minimum": 0,
  "pointer": "/delivered_artifact_envelope/revision",
  "value_kind": "INTEGER"
 },
 {
  "fields_exact": [
   "consumption_state",
   "effect_receipt_count",
   "effect_sha256",
   "execution_receipt_effect_sha256",
   "grant_expires_at",
   "grant_not_before",
   "invocation_nonce",
   "invocation_time",
   "prior_invocation_nonces",
   "revocation_checked_at",
   "revoked_at"
  ],
  "pointer": "/guard_observation_facts",
  "value_kind": "OBJECT"
 },
 {
  "enum": [
   "CONSUMED",
   "UNUSED"
  ],
  "pointer": "/guard_observation_facts/consumption_state",
  "value_kind": "STRING"
 },
 {
  "class_id": "SIGNED_NONNEGATIVE_INT64",
  "maximum": 9223372036854775807,
  "minimum": 0,
  "pointer": "/guard_observation_facts/effect_receipt_count",
  "value_kind": "INTEGER"
 },
 {
  "class_id": "SIGNED_NONNEGATIVE_INT64",
  "maximum": 9223372036854775807,
  "minimum": 0,
  "pointer": "/guard_observation_facts/grant_expires_at",
  "value_kind": "INTEGER"
 },
 {
  "class_id": "SIGNED_NONNEGATIVE_INT64",
  "maximum": 9223372036854775807,
  "minimum": 0,
  "pointer": "/guard_observation_facts/grant_not_before",
  "value_kind": "INTEGER"
 },
 {
  "class_id": "SIGNED_NONNEGATIVE_INT64",
  "maximum": 9223372036854775807,
  "minimum": 0,
  "pointer": "/guard_observation_facts/invocation_time",
  "value_kind": "INTEGER"
 },
 {
  "maximum": 9223372036854775807,
  "minimum": 0,
  "pointer": "/guard_observation_facts/revocation_checked_at",
  "value_kind": "INTEGER_OR_NULL"
 },
 {
  "maximum": 9223372036854775807,
  "minimum": 0,
  "pointer": "/guard_observation_facts/revoked_at",
  "value_kind": "INTEGER_OR_NULL"
 },
 {
  "class_id": "SHA256_UPPER",
  "pointer": "/guard_observation_facts/effect_sha256",
  "value_kind": "STRING"
 },
 {
  "class_id": "SHA256_UPPER",
  "pointer": "/guard_observation_facts/execution_receipt_effect_sha256",
  "value_kind": "STRING"
 },
 {
  "class_id": "IDENTIFIER",
  "pointer": "/guard_observation_facts/invocation_nonce",
  "value_kind": "STRING"
 },
 {
  "class_id": "SET_IDENTIFIER_ARRAY",
  "maximum": 256,
  "minimum": 0,
  "pointer": "/guard_observation_facts/prior_invocation_nonces",
  "unique": True,
  "utf8_sorted": True,
  "value_kind": "ARRAY"
 },
 {
  "fields_exact": [
   "attempt_ordinal",
   "refetch_budget"
  ],
  "pointer": "/remediation",
  "value_kind": "OBJECT"
 },
 {
  "class_id": "SIGNED_NONNEGATIVE_INT64",
  "maximum": 9223372036854775807,
  "minimum": 0,
  "pointer": "/remediation/attempt_ordinal",
  "value_kind": "INTEGER"
 },
 {
  "class_id": "EXACT_RANGE_0_1",
  "maximum": 1,
  "minimum": 0,
  "pointer": "/remediation/refetch_budget",
  "value_kind": "INTEGER"
 },
 {
  "fields_exact": [
   "declared_sha256",
   "delivered_artifact_id",
   "delivered_revision",
   "requested_artifact_id",
   "requested_revision"
  ],
  "pointer": "/requested_delivered_transfer",
  "value_kind": "OBJECT"
 },
 {
  "class_id": "SHA256_UPPER",
  "pointer": "/requested_delivered_transfer/declared_sha256",
  "value_kind": "STRING"
 },
 {
  "class_id": "IDENTIFIER",
  "pointer": "/requested_delivered_transfer/delivered_artifact_id",
  "value_kind": "STRING"
 },
 {
  "class_id": "IDENTIFIER",
  "pointer": "/requested_delivered_transfer/requested_artifact_id",
  "value_kind": "STRING"
 },
 {
  "class_id": "REVISION",
  "maximum": 2147483647,
  "minimum": 0,
  "pointer": "/requested_delivered_transfer/delivered_revision",
  "value_kind": "INTEGER"
 },
 {
  "class_id": "REVISION",
  "maximum": 2147483647,
  "minimum": 0,
  "pointer": "/requested_delivered_transfer/requested_revision",
  "value_kind": "INTEGER"
 },
 {
  "fields_exact": [
   "format",
   "source_artifact_id",
   "source_revision",
   "source_sha256"
  ],
  "pointer": "/source_lineage_observation",
  "value_kind": "OBJECT"
 },
 {
  "const": "RR-SCIENTIFIC-CLOSED-LINEAGE-OBSERVATION-1",
  "pointer": "/source_lineage_observation/format",
  "value_kind": "STRING"
 },
 {
  "class_id": "IDENTIFIER",
  "pointer": "/source_lineage_observation/source_artifact_id",
  "value_kind": "STRING"
 },
 {
  "class_id": "REVISION",
  "maximum": 2147483647,
  "minimum": 0,
  "pointer": "/source_lineage_observation/source_revision",
  "value_kind": "INTEGER"
 },
 {
  "class_id": "SHA256_UPPER",
  "pointer": "/source_lineage_observation/source_sha256",
  "value_kind": "STRING"
 },
 {
  "fields_exact": [
   "constraints",
   "instruction"
  ],
  "pointer": "/task_instruction_constraints",
  "value_kind": "OBJECT"
 },
 {
  "class_id": "ORDERED_STRING_ARRAY",
  "maximum": 32,
  "member_utf8_maximum": 512,
  "member_utf8_minimum": 1,
  "minimum": 0,
  "pointer": "/task_instruction_constraints/constraints",
  "value_kind": "ARRAY"
 },
 {
  "pointer": "/task_instruction_constraints/instruction",
  "utf8_maximum": 4096,
  "utf8_minimum": 1,
  "value_kind": "STRING"
 },
 {
  "class_id": "PARENT_DIGEST_IDENTIFIER",
  "pointer": "/comparison_facts/expected_direct_parents/*",
  "value_kind": "STRING"
 },
 {
  "class_id": "IDENTIFIER",
  "pointer": "/comparison_facts/observed_direct_parents/*",
  "value_kind": "STRING"
 },
 {
  "class_id": "IDENTIFIER",
  "pointer": "/comparison_facts/expected_scope/*",
  "value_kind": "STRING"
 },
 {
  "class_id": "IDENTIFIER",
  "pointer": "/comparison_facts/observed_scope/*",
  "value_kind": "STRING"
 },
 {
  "class_id": "IDENTIFIER",
  "pointer": "/guard_observation_facts/prior_invocation_nonces/*",
  "value_kind": "STRING"
 },
 {
  "pointer": "/task_instruction_constraints/constraints/*",
  "utf8_maximum": 512,
  "utf8_minimum": 1,
  "value_kind": "STRING"
 }
]

STATE_R_ROWS = [
 {
  "fields_exact": [
   "format"
  ],
  "pointer": "",
  "value_kind": "OBJECT"
 },
 {
  "const": "RR-STUDY-TREATMENT-STATE-R-5",
  "pointer": "/format",
  "value_kind": "STRING"
 }
]

STATE_S_ROWS = [
 {
  "fields_exact": [
   "format",
   "operating_threshold"
  ],
  "pointer": "",
  "value_kind": "OBJECT"
 },
 {
  "const": "RR-STUDY-TREATMENT-STATE-S-5",
  "pointer": "/format",
  "value_kind": "STRING"
 },
 {
  "class_id": "OUTER_THRESHOLD",
  "maximum": 17,
  "minimum": 0,
  "pointer": "/operating_threshold",
  "value_kind": "INTEGER"
 }
]

STATE_U_ROWS = [
 {
  "fields_exact": [
   "format"
  ],
  "pointer": "",
  "value_kind": "OBJECT"
 },
 {
  "const": "RR-STUDY-TREATMENT-STATE-U-5",
  "pointer": "/format",
  "value_kind": "STRING"
 }
]
