"""Verbatim transcription of the frozen authority's document_schemas.

Source: RR_STUDY_TREATMENT_V6_SEMANTIC_AUTHORITY_DRAFT.json, key path
``document_schemas``, size 140172 B / SHA-256
E233C6373B34F11C5D12B51EAEE501F1042F46D87E2AE6853812790004F55AC8.
Generated mechanically so that no row is mis-transcribed; the values are the
authority's own and carry no added reading.
"""

DOCUMENT_SCHEMAS = {'COMMON': {'closed_value_kind_vocabulary': ['ARRAY',
                                             'BOOLEAN',
                                             'INTEGER',
                                             'NULL',
                                             'OBJECT',
                                             'STRING'],
            'cross_field': 'Delivered envelope id/revision equal '
                           'requested_delivered_transfer delivered id/revision. '
                           'application/json content decodes to admitted JCS. '
                           'valid_from_ns <= valid_until_ns. Baseline expected '
                           'receiver/purpose/scope values are exact substitutions from '
                           'the selected A5 raw world; observed values remain '
                           'independently typed observations and may differ so S '
                           'mismatch predicates are reachable. Common contains none of '
                           'arm,assignment,treatment,module_identity,expected_result,outcome,oracle,truth,gold,seed_label,scorer_state,post_treatment,selected_threshold,candidate_path,candidate_sha256,proof_path,proof_sha256,manifest,source_files.',
            'cross_field_laws': [{'condition': '/delivered_artifact_envelope/artifact_id '
                                               'equals '
                                               '/requested_delivered_transfer/delivered_artifact_id',
                                  'law_id': 'DELIVERED_ID'},
                                 {'condition': '/delivered_artifact_envelope/revision '
                                               'equals '
                                               '/requested_delivered_transfer/delivered_revision',
                                  'law_id': 'DELIVERED_REVISION'},
                                 {'condition': 'If media_type is application/json, '
                                               'strict base64 decode content_b64 and '
                                               'require decoded bytes equal admitted '
                                               'JCS for their parsed value.',
                                  'law_id': 'JSON_CONTENT'},
                                 {'condition': '/comparison_facts/valid_from_ns <= '
                                               '/comparison_facts/valid_until_ns',
                                  'law_id': 'INTERVAL'},
                                 {'condition': '/comparison_facts/expected_receiver_capability '
                                               'is a receiver_capability_id in '
                                               'selected A5 /domain_vocabulary and '
                                               'equals selected '
                                               '/use_records/0/receiver_capability_id',
                                  'law_id': 'RECEIVER_VOCAB'},
                                 {'condition': '/comparison_facts/expected_purpose is '
                                               'a purpose_id in selected A5 '
                                               '/domain_vocabulary and equals selected '
                                               '/use_records/0/purpose_id',
                                  'law_id': 'PURPOSE_VOCAB'},
                                 {'condition': 'Every /comparison_facts/expected_scope '
                                               'member is a scope_id in selected A5 '
                                               '/domain_vocabulary and the array '
                                               'equals [selected '
                                               '/use_records/0/scope_id]',
                                  'law_id': 'SCOPE_VOCAB'}],
            'field_schema_rows': [{'fields_exact': ['a2_raw_shared_bundle',
                                                    'comparison_facts',
                                                    'delivered_artifact_envelope',
                                                    'format',
                                                    'guard_observation_facts',
                                                    'remediation',
                                                    'requested_delivered_transfer',
                                                    'source_lineage_observation',
                                                    'task_id',
                                                    'task_instruction_constraints'],
                                   'pointer': '',
                                   'value_kind': 'OBJECT'},
                                  {'accepted_schema_path': 'access/A2_SHARED_DOMAIN_VOCABULARY_BASELINE_PROJECTION_0_1.schema.json',
                                   'accepted_schema_sha256': '1449369AE3CC4458F3F904ADCF0F24B0685E86C65EAC2AE656F7A3E4AD946460',
                                   'additional_properties': False,
                                   'pointer': '/a2_raw_shared_bundle',
                                   'value_kind': 'OBJECT'},
                                  {'const': 'RR-STUDY-TREATMENT-COMMON-5',
                                   'pointer': '/format',
                                   'value_kind': 'STRING'},
                                  {'class_id': 'IDENTIFIER',
                                   'pointer': '/task_id',
                                   'value_kind': 'STRING'},
                                  {'fields_exact': ['carrier_fence',
                                                    'consumed_representation_sha256',
                                                    'current_fence',
                                                    'expected_action_class',
                                                    'expected_authority',
                                                    'expected_carrier',
                                                    'expected_direct_parents',
                                                    'expected_generation',
                                                    'expected_owner',
                                                    'expected_principal',
                                                    'expected_purpose',
                                                    'expected_receiver_capability',
                                                    'expected_representation_sha256',
                                                    'expected_route',
                                                    'expected_scope',
                                                    'expected_slot',
                                                    'observed_action_class',
                                                    'observed_authority',
                                                    'observed_carrier',
                                                    'observed_direct_parents',
                                                    'observed_generation',
                                                    'observed_owner',
                                                    'observed_principal',
                                                    'observed_purpose',
                                                    'observed_receiver_capability',
                                                    'observed_route',
                                                    'observed_scope',
                                                    'observed_slot',
                                                    'origin_finalized',
                                                    'revocation_active',
                                                    'use_time_ns',
                                                    'valid_from_ns',
                                                    'valid_until_ns'],
                                   'pointer': '/comparison_facts',
                                   'value_kind': 'OBJECT'},
                                  {'class_id': 'SIGNED_NONNEGATIVE_INT64',
                                   'maximum': 9223372036854775807,
                                   'minimum': 0,
                                   'pointer': '/comparison_facts/carrier_fence',
                                   'value_kind': 'INTEGER'},
                                  {'class_id': 'SIGNED_NONNEGATIVE_INT64',
                                   'maximum': 9223372036854775807,
                                   'minimum': 0,
                                   'pointer': '/comparison_facts/current_fence',
                                   'value_kind': 'INTEGER'},
                                  {'class_id': 'SIGNED_NONNEGATIVE_INT64',
                                   'maximum': 9223372036854775807,
                                   'minimum': 0,
                                   'pointer': '/comparison_facts/expected_generation',
                                   'value_kind': 'INTEGER'},
                                  {'class_id': 'SIGNED_NONNEGATIVE_INT64',
                                   'maximum': 9223372036854775807,
                                   'minimum': 0,
                                   'pointer': '/comparison_facts/observed_generation',
                                   'value_kind': 'INTEGER'},
                                  {'class_id': 'SIGNED_NONNEGATIVE_INT64',
                                   'maximum': 9223372036854775807,
                                   'minimum': 0,
                                   'pointer': '/comparison_facts/use_time_ns',
                                   'value_kind': 'INTEGER'},
                                  {'class_id': 'SIGNED_NONNEGATIVE_INT64',
                                   'maximum': 9223372036854775807,
                                   'minimum': 0,
                                   'pointer': '/comparison_facts/valid_from_ns',
                                   'value_kind': 'INTEGER'},
                                  {'class_id': 'SIGNED_NONNEGATIVE_INT64',
                                   'maximum': 9223372036854775807,
                                   'minimum': 0,
                                   'pointer': '/comparison_facts/valid_until_ns',
                                   'value_kind': 'INTEGER'},
                                  {'pointer': '/comparison_facts/origin_finalized',
                                   'value_kind': 'BOOLEAN'},
                                  {'pointer': '/comparison_facts/revocation_active',
                                   'value_kind': 'BOOLEAN'},
                                  {'class_id': 'SHA256_UPPER',
                                   'pointer': '/comparison_facts/consumed_representation_sha256',
                                   'value_kind': 'STRING'},
                                  {'class_id': 'SHA256_UPPER',
                                   'pointer': '/comparison_facts/expected_representation_sha256',
                                   'value_kind': 'STRING'},
                                  {'class_id': 'ORDERED_IDENTIFIER_ARRAY',
                                   'maximum': 256,
                                   'minimum': 0,
                                   'pointer': '/comparison_facts/expected_direct_parents',
                                   'value_kind': 'ARRAY'},
                                  {'class_id': 'ORDERED_IDENTIFIER_ARRAY',
                                   'maximum': 256,
                                   'minimum': 0,
                                   'pointer': '/comparison_facts/observed_direct_parents',
                                   'value_kind': 'ARRAY'},
                                  {'class_id': 'SET_IDENTIFIER_ARRAY',
                                   'maximum': 256,
                                   'minimum': 1,
                                   'pointer': '/comparison_facts/expected_scope',
                                   'unique': True,
                                   'utf8_sorted': True,
                                   'value_kind': 'ARRAY'},
                                  {'class_id': 'SET_IDENTIFIER_ARRAY',
                                   'maximum': 256,
                                   'minimum': 1,
                                   'pointer': '/comparison_facts/observed_scope',
                                   'unique': True,
                                   'utf8_sorted': True,
                                   'value_kind': 'ARRAY'},
                                  {'class_id': 'IDENTIFIER',
                                   'pointer': '/comparison_facts/expected_action_class',
                                   'value_kind': 'STRING'},
                                  {'class_id': 'IDENTIFIER',
                                   'pointer': '/comparison_facts/expected_authority',
                                   'value_kind': 'STRING'},
                                  {'class_id': 'IDENTIFIER',
                                   'pointer': '/comparison_facts/expected_carrier',
                                   'value_kind': 'STRING'},
                                  {'class_id': 'IDENTIFIER',
                                   'pointer': '/comparison_facts/expected_owner',
                                   'value_kind': 'STRING'},
                                  {'class_id': 'IDENTIFIER',
                                   'pointer': '/comparison_facts/expected_principal',
                                   'value_kind': 'STRING'},
                                  {'class_id': 'IDENTIFIER',
                                   'pointer': '/comparison_facts/expected_purpose',
                                   'value_kind': 'STRING'},
                                  {'class_id': 'IDENTIFIER',
                                   'pointer': '/comparison_facts/expected_receiver_capability',
                                   'value_kind': 'STRING'},
                                  {'class_id': 'IDENTIFIER',
                                   'pointer': '/comparison_facts/expected_route',
                                   'value_kind': 'STRING'},
                                  {'class_id': 'IDENTIFIER',
                                   'pointer': '/comparison_facts/expected_slot',
                                   'value_kind': 'STRING'},
                                  {'class_id': 'IDENTIFIER',
                                   'pointer': '/comparison_facts/observed_action_class',
                                   'value_kind': 'STRING'},
                                  {'class_id': 'IDENTIFIER',
                                   'pointer': '/comparison_facts/observed_authority',
                                   'value_kind': 'STRING'},
                                  {'class_id': 'IDENTIFIER',
                                   'pointer': '/comparison_facts/observed_carrier',
                                   'value_kind': 'STRING'},
                                  {'class_id': 'IDENTIFIER',
                                   'pointer': '/comparison_facts/observed_owner',
                                   'value_kind': 'STRING'},
                                  {'class_id': 'IDENTIFIER',
                                   'pointer': '/comparison_facts/observed_principal',
                                   'value_kind': 'STRING'},
                                  {'class_id': 'IDENTIFIER',
                                   'pointer': '/comparison_facts/observed_purpose',
                                   'value_kind': 'STRING'},
                                  {'class_id': 'IDENTIFIER',
                                   'pointer': '/comparison_facts/observed_receiver_capability',
                                   'value_kind': 'STRING'},
                                  {'class_id': 'IDENTIFIER',
                                   'pointer': '/comparison_facts/observed_route',
                                   'value_kind': 'STRING'},
                                  {'class_id': 'IDENTIFIER',
                                   'pointer': '/comparison_facts/observed_slot',
                                   'value_kind': 'STRING'},
                                  {'fields_exact': ['artifact_id',
                                                    'content_b64',
                                                    'format',
                                                    'media_type',
                                                    'revision'],
                                   'pointer': '/delivered_artifact_envelope',
                                   'value_kind': 'OBJECT'},
                                  {'class_id': 'IDENTIFIER',
                                   'pointer': '/delivered_artifact_envelope/artifact_id',
                                   'value_kind': 'STRING'},
                                  {'class_id': 'CANONICAL_BASE64',
                                   'decoded_maximum': 32768,
                                   'decoded_minimum': 1,
                                   'pointer': '/delivered_artifact_envelope/content_b64',
                                   'value_kind': 'STRING'},
                                  {'const': 'RR-SCIENTIFIC-CLOSED-ARTIFACT-1',
                                   'pointer': '/delivered_artifact_envelope/format',
                                   'value_kind': 'STRING'},
                                  {'enum': ['application/json', 'text/plain'],
                                   'pointer': '/delivered_artifact_envelope/media_type',
                                   'value_kind': 'STRING'},
                                  {'class_id': 'REVISION',
                                   'maximum': 2147483647,
                                   'minimum': 0,
                                   'pointer': '/delivered_artifact_envelope/revision',
                                   'value_kind': 'INTEGER'},
                                  {'fields_exact': ['consumption_state',
                                                    'effect_receipt_count',
                                                    'effect_sha256',
                                                    'execution_receipt_effect_sha256',
                                                    'grant_expires_at',
                                                    'grant_not_before',
                                                    'invocation_nonce',
                                                    'invocation_time',
                                                    'prior_invocation_nonces',
                                                    'revocation_checked_at',
                                                    'revoked_at'],
                                   'pointer': '/guard_observation_facts',
                                   'value_kind': 'OBJECT'},
                                  {'enum': ['CONSUMED', 'UNUSED'],
                                   'pointer': '/guard_observation_facts/consumption_state',
                                   'value_kind': 'STRING'},
                                  {'class_id': 'SIGNED_NONNEGATIVE_INT64',
                                   'maximum': 9223372036854775807,
                                   'minimum': 0,
                                   'pointer': '/guard_observation_facts/effect_receipt_count',
                                   'value_kind': 'INTEGER'},
                                  {'class_id': 'SIGNED_NONNEGATIVE_INT64',
                                   'maximum': 9223372036854775807,
                                   'minimum': 0,
                                   'pointer': '/guard_observation_facts/grant_expires_at',
                                   'value_kind': 'INTEGER'},
                                  {'class_id': 'SIGNED_NONNEGATIVE_INT64',
                                   'maximum': 9223372036854775807,
                                   'minimum': 0,
                                   'pointer': '/guard_observation_facts/grant_not_before',
                                   'value_kind': 'INTEGER'},
                                  {'class_id': 'SIGNED_NONNEGATIVE_INT64',
                                   'maximum': 9223372036854775807,
                                   'minimum': 0,
                                   'pointer': '/guard_observation_facts/invocation_time',
                                   'value_kind': 'INTEGER'},
                                  {'maximum': 9223372036854775807,
                                   'minimum': 0,
                                   'pointer': '/guard_observation_facts/revocation_checked_at',
                                   'value_kind': 'INTEGER_OR_NULL'},
                                  {'maximum': 9223372036854775807,
                                   'minimum': 0,
                                   'pointer': '/guard_observation_facts/revoked_at',
                                   'value_kind': 'INTEGER_OR_NULL'},
                                  {'class_id': 'SHA256_UPPER',
                                   'pointer': '/guard_observation_facts/effect_sha256',
                                   'value_kind': 'STRING'},
                                  {'class_id': 'SHA256_UPPER',
                                   'pointer': '/guard_observation_facts/execution_receipt_effect_sha256',
                                   'value_kind': 'STRING'},
                                  {'class_id': 'IDENTIFIER',
                                   'pointer': '/guard_observation_facts/invocation_nonce',
                                   'value_kind': 'STRING'},
                                  {'class_id': 'SET_IDENTIFIER_ARRAY',
                                   'maximum': 256,
                                   'minimum': 0,
                                   'pointer': '/guard_observation_facts/prior_invocation_nonces',
                                   'unique': True,
                                   'utf8_sorted': True,
                                   'value_kind': 'ARRAY'},
                                  {'fields_exact': ['attempt_ordinal',
                                                    'refetch_budget'],
                                   'pointer': '/remediation',
                                   'value_kind': 'OBJECT'},
                                  {'class_id': 'SIGNED_NONNEGATIVE_INT64',
                                   'maximum': 9223372036854775807,
                                   'minimum': 0,
                                   'pointer': '/remediation/attempt_ordinal',
                                   'value_kind': 'INTEGER'},
                                  {'class_id': 'EXACT_RANGE_0_1',
                                   'maximum': 1,
                                   'minimum': 0,
                                   'pointer': '/remediation/refetch_budget',
                                   'value_kind': 'INTEGER'},
                                  {'fields_exact': ['declared_sha256',
                                                    'delivered_artifact_id',
                                                    'delivered_revision',
                                                    'requested_artifact_id',
                                                    'requested_revision'],
                                   'pointer': '/requested_delivered_transfer',
                                   'value_kind': 'OBJECT'},
                                  {'class_id': 'SHA256_UPPER',
                                   'pointer': '/requested_delivered_transfer/declared_sha256',
                                   'value_kind': 'STRING'},
                                  {'class_id': 'IDENTIFIER',
                                   'pointer': '/requested_delivered_transfer/delivered_artifact_id',
                                   'value_kind': 'STRING'},
                                  {'class_id': 'IDENTIFIER',
                                   'pointer': '/requested_delivered_transfer/requested_artifact_id',
                                   'value_kind': 'STRING'},
                                  {'class_id': 'REVISION',
                                   'maximum': 2147483647,
                                   'minimum': 0,
                                   'pointer': '/requested_delivered_transfer/delivered_revision',
                                   'value_kind': 'INTEGER'},
                                  {'class_id': 'REVISION',
                                   'maximum': 2147483647,
                                   'minimum': 0,
                                   'pointer': '/requested_delivered_transfer/requested_revision',
                                   'value_kind': 'INTEGER'},
                                  {'fields_exact': ['format',
                                                    'source_artifact_id',
                                                    'source_revision',
                                                    'source_sha256'],
                                   'pointer': '/source_lineage_observation',
                                   'value_kind': 'OBJECT'},
                                  {'const': 'RR-SCIENTIFIC-CLOSED-LINEAGE-OBSERVATION-1',
                                   'pointer': '/source_lineage_observation/format',
                                   'value_kind': 'STRING'},
                                  {'class_id': 'IDENTIFIER',
                                   'pointer': '/source_lineage_observation/source_artifact_id',
                                   'value_kind': 'STRING'},
                                  {'class_id': 'REVISION',
                                   'maximum': 2147483647,
                                   'minimum': 0,
                                   'pointer': '/source_lineage_observation/source_revision',
                                   'value_kind': 'INTEGER'},
                                  {'class_id': 'SHA256_UPPER',
                                   'pointer': '/source_lineage_observation/source_sha256',
                                   'value_kind': 'STRING'},
                                  {'fields_exact': ['constraints', 'instruction'],
                                   'pointer': '/task_instruction_constraints',
                                   'value_kind': 'OBJECT'},
                                  {'class_id': 'ORDERED_STRING_ARRAY',
                                   'maximum': 32,
                                   'member_utf8_maximum': 512,
                                   'member_utf8_minimum': 1,
                                   'minimum': 0,
                                   'pointer': '/task_instruction_constraints/constraints',
                                   'value_kind': 'ARRAY'},
                                  {'pointer': '/task_instruction_constraints/instruction',
                                   'utf8_maximum': 4096,
                                   'utf8_minimum': 1,
                                   'value_kind': 'STRING'},
                                  {'class_id': 'PARENT_DIGEST_IDENTIFIER',
                                   'pointer': '/comparison_facts/expected_direct_parents/*',
                                   'value_kind': 'STRING'},
                                  {'class_id': 'IDENTIFIER',
                                   'pointer': '/comparison_facts/observed_direct_parents/*',
                                   'value_kind': 'STRING'},
                                  {'class_id': 'IDENTIFIER',
                                   'pointer': '/comparison_facts/expected_scope/*',
                                   'value_kind': 'STRING'},
                                  {'class_id': 'IDENTIFIER',
                                   'pointer': '/comparison_facts/observed_scope/*',
                                   'value_kind': 'STRING'},
                                  {'class_id': 'IDENTIFIER',
                                   'pointer': '/guard_observation_facts/prior_invocation_nonces/*',
                                   'value_kind': 'STRING'},
                                  {'pointer': '/task_instruction_constraints/constraints/*',
                                   'utf8_maximum': 512,
                                   'utf8_minimum': 1,
                                   'value_kind': 'STRING'}],
            'fields_exact': ['a2_raw_shared_bundle',
                             'comparison_facts',
                             'delivered_artifact_envelope',
                             'format',
                             'guard_observation_facts',
                             'remediation',
                             'requested_delivered_transfer',
                             'source_lineage_observation',
                             'task_id',
                             'task_instruction_constraints'],
            'format': 'RR-STUDY-TREATMENT-COMMON-5',
            'nested': {'comparison_facts': ['carrier_fence',
                                            'consumed_representation_sha256',
                                            'current_fence',
                                            'expected_action_class',
                                            'expected_authority',
                                            'expected_carrier',
                                            'expected_direct_parents',
                                            'expected_generation',
                                            'expected_owner',
                                            'expected_principal',
                                            'expected_purpose',
                                            'expected_receiver_capability',
                                            'expected_representation_sha256',
                                            'expected_route',
                                            'expected_scope',
                                            'expected_slot',
                                            'observed_action_class',
                                            'observed_authority',
                                            'observed_carrier',
                                            'observed_direct_parents',
                                            'observed_generation',
                                            'observed_owner',
                                            'observed_principal',
                                            'observed_purpose',
                                            'observed_receiver_capability',
                                            'observed_route',
                                            'observed_scope',
                                            'observed_slot',
                                            'origin_finalized',
                                            'revocation_active',
                                            'use_time_ns',
                                            'valid_from_ns',
                                            'valid_until_ns'],
                       'delivered_artifact_envelope': ['artifact_id',
                                                       'content_b64',
                                                       'format',
                                                       'media_type',
                                                       'revision'],
                       'guard_observation_facts': ['consumption_state',
                                                   'effect_receipt_count',
                                                   'effect_sha256',
                                                   'execution_receipt_effect_sha256',
                                                   'grant_expires_at',
                                                   'grant_not_before',
                                                   'invocation_nonce',
                                                   'invocation_time',
                                                   'prior_invocation_nonces',
                                                   'revocation_checked_at',
                                                   'revoked_at'],
                       'remediation': ['attempt_ordinal', 'refetch_budget'],
                       'requested_delivered_transfer': ['declared_sha256',
                                                        'delivered_artifact_id',
                                                        'delivered_revision',
                                                        'requested_artifact_id',
                                                        'requested_revision'],
                       'source_lineage_observation': ['format',
                                                      'source_artifact_id',
                                                      'source_revision',
                                                      'source_sha256'],
                       'task_instruction_constraints': ['constraints', 'instruction']},
            'types_and_values': 'The field_schema_rows are exhaustive for COMMON '
                                'except the complete pinned A2 subtree, whose exact '
                                'closed Draft-2020-12 schema is delegated by content '
                                'hash. A pointer matches exactly one row or one '
                                'accepted A2 schema node; zero or multiple matches '
                                'reject. INTEGER_OR_NULL is the explicit union only.'},
 'STATE_R': {'field_schema_rows': [{'fields_exact': ['format'],
                                    'pointer': '',
                                    'value_kind': 'OBJECT'},
                                   {'const': 'RR-STUDY-TREATMENT-STATE-R-5',
                                    'pointer': '/format',
                                    'value_kind': 'STRING'}],
             'fields_exact': ['format'],
             'format': 'RR-STUDY-TREATMENT-STATE-R-5'},
 'STATE_S': {'field_schema_rows': [{'fields_exact': ['format', 'operating_threshold'],
                                    'pointer': '',
                                    'value_kind': 'OBJECT'},
                                   {'const': 'RR-STUDY-TREATMENT-STATE-S-5',
                                    'pointer': '/format',
                                    'value_kind': 'STRING'},
                                   {'class_id': 'OUTER_THRESHOLD',
                                    'maximum': 17,
                                    'minimum': 0,
                                    'pointer': '/operating_threshold',
                                    'value_kind': 'INTEGER'}],
             'fields_exact': ['format', 'operating_threshold'],
             'format': 'RR-STUDY-TREATMENT-STATE-S-5',
             'operating_threshold': 'integer 0..17; no default and no preferred value'},
 'STATE_U': {'field_schema_rows': [{'fields_exact': ['format'],
                                    'pointer': '',
                                    'value_kind': 'OBJECT'},
                                   {'const': 'RR-STUDY-TREATMENT-STATE-U-5',
                                    'pointer': '/format',
                                    'value_kind': 'STRING'}],
             'fields_exact': ['format'],
             'format': 'RR-STUDY-TREATMENT-STATE-U-5'}}

ACCEPTED_SOURCE_FILES = [{'byte_length': 19819,
  'path': 'receiver_reliance/__init__.py',
  'sha256': '635804FA4767D69FC6466736423AA68697B95FF37C618074B17DB54F8830C2EE'},
 {'byte_length': 2326,
  'path': 'receiver_reliance/engine_manifest.json',
  'sha256': '336775BACF9AFB944418DDB9B10B3B07D93A2B96B557263A4FFD26BD84C77585'},
 {'byte_length': 337,
  'path': 'rr_s_all_kernel/__init__.py',
  'sha256': '052E4896C1DE0B49535DB942939E88AA8EFB4B78A088792FDAF96FF026BCEAF3'},
 {'byte_length': 14416,
  'path': 'rr_full_treatment/static_kernel.py',
  'sha256': '3A71AE69E98E2247197D0505E28AD3719BC9061E6F0F33B1FC19A150159B11D0'},
 {'byte_length': 6314,
  'path': 'rr_s_all_qualification/import_graph.py',
  'sha256': 'BFFBF2942789C223B987A070A7E398D98E81D6703180DC992415D89F7D0724DB'}]

ENGINE_MANIFEST_EXACT_ROWS = [{'byte_length': 19051,
  'path': 'access/A2_SHARED_DOMAIN_VOCABULARY_BASELINE_PROJECTION_0_1.schema.json',
  'sha256': '1449369AE3CC4458F3F904ADCF0F24B0685E86C65EAC2AE656F7A3E4AD946460'},
 {'byte_length': 513384,
  'path': 'access/SANITIZED_PRIMARY_BASELINE_IMPLEMENTER_PACKET_0_1.json',
  'sha256': '73A4FF4DD8ABA41D0F68414CB754EFCDF9807FAE73354F1959420B16C5F359F3'},
 {'byte_length': 321451,
  'path': 'baseline-run/control/B1_PRIMARY_IMPLEMENTER_CONTRACT_0_1.json',
  'sha256': 'DCFCB0714E1A7E677548057987F604D227F791F3FC3E0EA89BE5ED932447F48E'},
 {'byte_length': 50314,
  'path': 'baseline-run/implementation-output-0.3/b1_capabilities.py',
  'sha256': '4D9FA1C9CCB60B980BCE1739FE8FDC10E84AEFC03D4C20E2AA1A8B0BBE2D18FC'},
 {'byte_length': 19327,
  'path': 'baseline-run/implementation-output-0.3/pcb_runner.py',
  'sha256': '83319385C8B6D28965F4683B8C0689FB70158E86ED35D54E7467E8E3DF076E09'},
 {'byte_length': 35399,
  'path': 'grounded-0_4/authority_register_0_4.json',
  'sha256': 'C3414FC751C3B5ECA43A4932C694641D801A21F2CF53C42BE3A8C87C234CF499'},
 {'byte_length': 8634,
  'path': 'grounded-0_4/authority_surface.py',
  'sha256': '62B689D964CA906C2E3F8376047E0DDD14C78364432B1A7EA8499C8FF7E8C5DD'},
 {'byte_length': 2329,
  'path': 'grounded-0_4/closures_0_4.json',
  'sha256': 'EBA198726DE960E9F59ACE5A7E1BDB701BFBA5B1BD09BC59FF4540F2B14E8F9C'},
 {'byte_length': 28523,
  'path': 'grounded-0_4/rr_api.py',
  'sha256': '79C0582FAB4A04DA3FCA90ECD7B5096457D67EBA4CA7E8D6A487C5D3E2CDECD3'},
 {'byte_length': 25976,
  'path': 'supplemental-0_3/control/B1_COMPOSED_CAPABILITY_MATRIX_0_3.json',
  'sha256': 'B369777E51B2A64DC2C304C5949F38E13956353B496BABA8B6E488451F8C5B98'},
 {'byte_length': 159277,
  'path': 'supplemental-0_3/control/B1_SUPPLEMENTAL_COMPARATOR_CONTRACT_0_3.json',
  'sha256': '6B2CAD02DDE7388D63D66E4863E5233CFBD1DC413575D9D260DB9799C7023A12'}]

ENGINE_MANIFEST_DECLARED_SHA256 = '4DEA5911A356E2492778964E140B3291784E8F1F896EE720B59847B182B1DD28'
ACCEPTED_SOURCE_FILES_ROOT = '0B80DFB9310BB6B5F3129D1917D6B0C8B4BC1173A9AB620707DE087E0A3DC3BA'
ACCEPTED_SOURCE_COMMIT = '3f39afbf4b62bc16359d0d88d14991be50bc5fb0'
